/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddDialogRocket: typeof import('./src/components/rocketComponents/AddDialogRocket.vue')['default']
    DrawerRocketDetail: typeof import('./src/components/rocketComponents/DrawerRocketDetail.vue')['default']
    EmptyHandler: typeof import('./src/components/errorComponent/EmptyHandler.vue')['default']
    ErrorHandler: typeof import('./src/components/errorComponent/ErrorHandler.vue')['default']
    FilterBarRocket: typeof import('./src/components/rocketComponents/FilterBarRocket.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LoadingHandler: typeof import('./src/components/errorComponent/LoadingHandler.vue')['default']
    RocketCard: typeof import('./src/components/rocketComponents/RocketCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
